# Site settings
title: Daniel Kisoon Kwon`s blog
email: moxie2ks@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://moxieDani.github.io" # the base hostname & protocol for your site

# Sidebar settings
description: Welcome!

# Social icons
facebook: moxie2ks
linkedin: moxie2ks
github: moxieDani
deviantart: -
codepen: -

footer: © Taken theme

# Build settings
markdown: kramdown
